title: Katalyst VC
description: Micro VC Fund for Scalable Impact
theme: jekyll-theme-minimal
# Add under existing config
nav:
  - title: "Home"
    url: "/"
  - title: "Resources"
    url: "/resources.md"
  - title: "Microloans"
    url: "/microloans.html"
  - title: "Origination"
    url: "/origination.html"
  - title: "Equity"
    url: "/equity.html"
  - title: "LP Capital"
    url: "/lpcapital.html"
  - title: "Grants"
    url: "/grants.html"
  - title: "Education"
    url: "/education.html"
  - title: "Advisory"
    url: "/advisory.html"
  - title: "Sponsorships"
    url: "/sponsorships.html"
  - title: "Contact"
    url: "/contact.html"